package com.neusoft.bsp.business.seller.mapper;

import com.neusoft.bsp.business.po.PackageInfo;
import com.neusoft.bsp.common.base.BaseMapper;
import org.springframework.stereotype.Repository;

//@CacheConfig(cacheNames="packageInfoCache")
@Repository
public interface PackageInfoMapper extends BaseMapper<Integer, PackageInfo>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @CacheEvict(allEntries = true, beforeInvocation = true)
    int deleteByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @CachePut()
    int insert(PackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @CachePut()
    int insertSelective(PackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @Cacheable()
    PackageInfo selectByPrimaryKey(Integer pckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @CachePut()
    int updateByPrimaryKeySelective(PackageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pck_package_info
     *
     * @mbg.generated
     */
//    @CachePut()
    int updateByPrimaryKey(PackageInfo record);

//    @Cacheable()
    PackageInfo getByProduct(int product_id);
}